Numpy array is much much faster than python list

In [4]:
import numpy as np

In [19]:
a = np.array([1,2,3], dtype = 'int16')
print(a)

[1 2 3]


In [8]:
b = np.array([[1,2,3], [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [12]:
a.ndim #results 1

1

Get dimension of b

In [13]:
b.ndim #results 2

2

Get Shape

In [14]:
a.shape

(3,)

In [15]:
b.shape

(2, 3)

Get type

In [20]:
a.dtype

dtype('int16')

Get size -> In bytes

In [23]:
a.itemsize

2

In [24]:
b.itemsize

4

Get total size

In [27]:
a.itemsize*a.size
# a.nbytes does the same

6

In [28]:
b.nbytes

24

Accessing Array elements, rows, columns etc

In [34]:
a = np.array([[12,23,34,5,3,54,2], [2,3,4,34,5,64,23]])
print(a)
a.size
a.shape

[[12 23 34  5  3 54  2]
 [ 2  3  4 34  5 64 23]]


(2, 7)

In [37]:
#Get a specific element
a[0,3]
a[0,-2] #Prints the 2nd last element of 0th row

54

In [38]:
#Get a specific row
a[0, :]

array([12, 23, 34,  5,  3, 54,  2])

In [39]:
#Get a specific column
a[:,0]

array([12,  2])

In [43]:
#Getting [startIndex:EndIndex:stepSize]
a[0, 1:6:2]

array([23,  5, 54])

In [45]:
#Updating single element
a[0,3] = 25
print(a)

[[12 23 34 25  3 54  2]
 [ 2  3  4 34  5 64 23]]


In [47]:
#Updating all column elements with same values
a[:, 2] = 5 # Updates the elements of 3rd column
print(a)

[[12 23  5 25  3 54  2]
 [ 2  3  5 34  5 64 23]]


In [48]:
#Updating all column elements with different values
a[:, 3] = [7, 8]
print(a)

[[12 23  5  7  3 54  2]
 [ 2  3  5  8  5 64 23]]


3D array

In [50]:
c = np.array([[[2,3],[5,6]],[[7,6],[8,9]]])
print(c)

[[[2 3]
  [5 6]]

 [[7 6]
  [8 9]]]


In [53]:
c.shape
c.ndim

3

In [54]:
#Get specific element
c[0,1,0]

5

In [60]:
#All 0s matrix
d = np.zeros(5)
d = np.zeros((5,2)) #5 rows, 2 columns
print(d)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [62]:
#All 1s matrix
d = np.ones((3,2))
print(d)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [63]:
#Initialize matrix with any number
d = np.full((2,2), 5)
print(d)

[[5 5]
 [5 5]]


In [65]:
#Initialize with any other number -> use shape of another array
d = np.full_like(a, 4)
print(d)

[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]


In [66]:
#Random decimal number
d = np.random.rand(4,3)
print(d)

[[0.6185995  0.81111657 0.29376417]
 [0.40968957 0.3564613  0.36241441]
 [0.7994829  0.04951065 0.95883148]
 [0.15836702 0.38163137 0.29903535]]


In [67]:
#Random decimal number using shape of another array
d = np.random.random_sample(a.shape)
print(d)

[[0.43431603 0.08760219 0.39930563 0.58113549 0.34620186 0.34878664
  0.96606086]
 [0.8748439  0.76039626 0.41762693 0.82060235 0.07223671 0.102735
  0.44928944]]


In [72]:
#Random integer values
d = np.random.randint(10, size=(3,3))  #10 is max int value
d = np.random.randint(5, 10, size=(3,3)) # range is 5 to 10
print(d)

[[8 9 5]
 [8 8 9]
 [6 9 9]]


In [73]:
#Identity matrix
d= np. identity(5)
print(d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [78]:
#Repeat
d = np.array([[1,2,3]])
r1 = np.repeat(d, 4, axis = 0) #d is repeated 4 times
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [86]:
#Building a matrix
output = np.ones((5,5))
print(output)
innerMat = np.zeros((3,3))
print(innerMat)
innerMat[1,1] = 9
print(innerMat)
#Merge output and innerMat
output[1:4, 1:4] = innerMat
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [99]:
#array copy
# a = d
# a[0,1] = 5
# print(d) # d should not be changed, but d is changing here
#So we should use .copy() function
a = d.copy()
a[0,1] = 15
print(d) # d is not changing
print(a)

[[1 5 3]]
[[ 1 15  3]]


List to numpy array

In [5]:
l1 = [1,2,3]
l2 = [4,5,6]
arr1 = np.array(l1)
arr2 = np.array(l2)
print(arr1)

[1 2 3]


Numpy array to list

In [6]:
arrToList = list(arr1)
print(arrToList)

[1, 2, 3]


Broadcast error