In [2]:
import numpy as np

In [102]:
a = np.array([1,2,3,4])
a+2 #add 2 to all elements

array([3, 4, 5, 6])

In [103]:
a-2

array([-1,  0,  1,  2])

In [104]:
a*2

array([2, 4, 6, 8])

In [105]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [109]:
b = np.array([1,0,1, 2])
a+b

array([2, 2, 4, 6])

In [110]:
a**2 #a power 2

array([ 1,  4,  9, 16])

In [111]:
np.sin(a) #Sine(angle) = result

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

Linear Algebra

In [12]:
#Matrix multiplication
mat1 = np.full((3,3), 2)
mat2 = np.full((3,3), 3)
np.matmul(mat1,mat2)

array([[18, 18, 18],
       [18, 18, 18],
       [18, 18, 18]])

In [23]:
#Determinant
arr = np.array([[2,3],[5,4]]) 
# arr.shape
det = np.linalg.det(arr)
print(det)

-6.999999999999999


1.0

Statistics

In [24]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
#Get minimum value
np.min(stats)

array([1, 4])

In [26]:
#Get maximum value
np.max(stats)

6

In [33]:
#Get minimum value from all rows
np.min(stats, axis=1) 
#np.min(stats, axis=1)  #Results minimum from all columns

array([1, 4])

In [34]:
#Get maximum value from all rows
np.max(stats, axis=1) 

array([3, 6])

In [36]:
#get sum
np.sum(stats, axis = 1)

array([ 6, 15])

Reorganizing Arrays

In [45]:
before = np.array([[1,2,3,4],[6,7,8,9]])
print(before)
after = before.reshape((8,1)) # 8 rows, 1 colums
print(after)

[[1 2 3 4]
 [6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [6]
 [7]
 [8]
 [9]]


In [51]:
#Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([6,7,8,9])
combine = np.vstack([v2,v1, v1,v2])  #Combined to one array of two rows
print(combine)

[[6 7 8 9]
 [1 2 3 4]
 [1 2 3 4]
 [6 7 8 9]]


In [54]:
#Horizontal stack
combine = np.hstack((v1,v2, v1, v2))
print(combine) #Combined to single column

[1 2 3 4 6 7 8 9 1 2 3 4 6 7 8 9]


In [55]:
#Vector dot product
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
dot = np.dot(arr1,arr2)
print(dot)

32


In [58]:
#dot product using @
dot = arr1 @ arr2
print(dot)

32
